apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  config.json: |-
    {
        "system": {
          "host": {{ .Values.ingress.host | quote }},
          "port": "443",
          "protocol": "https",
          "logger" : {
            "level" : "debug",
            "type": "console"
          },
          "subDomainCookies": false
        },
        "express":{
          "key" : "${EXPRESS_KEY}"
        },
        "gcm" : {
          "jid": "something@gcm.googleapis.com",
          "password": "password"
        },
        "ifttt" : {
          "iftttChannelKey" : "key",
          "iftttTestToken" : "token"
        },
        "mongodb": {
            "hosts": ["{{ include "helm-openhab-cloud.fullname" . }}-mongodb"],
            "db": "openhab",
            "user": "openhab",
            "password": "123_openHAB"
        },
        "redis": {
            "host": "{{ include "helm-openhab-cloud.fullname" . }}-redis",
            "port": "6379",
            "password": "123_openHAB"
        },
        "mailer": {
            "host" : "smtp",
            "port": 465,
            "secureConnection": true,
            "user": "${SMTP_USER}",
            "password": "${SMTP_PASSWORD}",
            "from": "openHAB Cloud <your@email.address>"
        },
        "legal": {
          "terms" : "",
            "policy": ""
        },
        "registration_enabled": true
    }
