apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-openhab-cloud.fullname" . }}-redis
  labels:
    {{- include "helm-openhab-cloud.labels" . | nindent 4 }}
spec:
  replicas: {{ default "1"  .Values.redis.replicaCount }}
  selector:
    matchLabels:
      {{- include "helm-openhab-cloud.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helm-openhab-cloud.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.redis.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "helm-openhab-cloud.serviceAccountName" . }}-redis
      securityContext:
        {{- toYaml .Values.redis.podSecurityContext | nindent 8 }}
      containers:
        - name: redis
          securityContext:
            {{- toYaml .Values.redis.securityContext | nindent 12 }}
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          {{- if .Values.redis.env }}
          env:
            {{- toYaml .Values.redis.env | nindent 12 }}
          {{- end}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
