apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-openhab-cloud.fullname" . }}-mongodb
  labels:
    {{- include "helm-openhab-cloud.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mongodb.service.type }}
  ports:
    - port: {{ .Values.mongodb.service.port }}
      targetPort: port
      protocol: TCP
      name: port
  selector:
    {{- include "helm-openhab-cloud.selectorLabels" . | nindent 4 }}
