apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-openhab-cloud.fullname" . }}-redis
  labels:
    {{- include "helm-openhab-cloud.labels" . | nindent 4 }}
spec:
  type: {{ .Values.redis.service.type }}
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "helm-openhab-cloud.selectorLabels" . | nindent 4 }}
